### ISSUE TITLE
Invalid insert query for an entity only with auto generated ID column.

### ISSUE THREAD

**Issue by bufferings** [seasarorg/doma#18]
Hi,

It seems that Doma creates wrong insert sql for an entity only with auto generated ID column like this:
```
insert into ID_ONLY) values)
```

It might be better to generate following query:
```
insert into ID_ONLY() values ()
```

I'm glad if you kindly share your opinion about this issue.
I will send a pull request.

**Comment by nakamura-to** [comment]
Closed by #19
