### ISSUE TITLE
SQLの先頭に自動でコメントを付与したい

### ISSUE THREAD

**Issue by tatsus** [seasarorg/doma#20]
はじめまして。

以下の要望が現在の仕組みで実現可能かお聞きしたいです。
もしくは、今後の機能拡張案としていただけると幸いです。

要望：SQLの先頭に自動でコメントを付与したいです。

理由：RDB側でリストアップされた遅いSQLの先頭にあるコメントを見て、
　　　アプリ側（該当SQLの実行元）と紐付けたいためです。
　　　リストアップされたSQLは後ろが切れたりWhere句が変わるため、該当SQLを探すのが困難です。

備考：コメントはRDB側とアプリ側で紐付け出来れば何でも構いません。
　　　SQLファイルパスが付与できれば分かりやすいです。
　　　主にSQL数が多く、似たSQLが多いアプリケーションで需要があると考えます。
　　　パフォーマンス問題が発生した際、該当SQLの実行元を調査する際に有用です。
　　　手動でコメントを付与するのは、量の多さや記法の不統一の恐れから避けたいです。
　　　Domaで実現せず、アプリとDBを透過的に監視するソリューションを使う案もあるとは思います。

自身で変更する場合の案：
　　　ソースを拝見した限りでは、prepareSqlメソッドの付近で処理を新規追加するのが楽だと思いました。
　　　見栄えを考えると、DaoImplクラスの__query.set*** の並びにあると分かりやすいと思いました。

**Comment by nakamura-to** [comment]
### 現在の仕組みで実現する場合

現在の実装では [AbstractSqlFileRepository.javaの132行目](https://github.com/seasarorg/doma/blob/1.38.0/doma/src/main/java/org/seasar/doma/jdbc/AbstractSqlFileRepository.java#L132) のメソッドでファイルからSQLを読み取っています。このメソッドの戻り値でコメントを付与したSQLを返す方法はいかがでしょうか？

ただし、残念なことに `AbstractSqlFileRepository` は `final` なメソッドが多く拡張しづらいので `final`  を外したコピーを別クラスとして作成し、コメントを付与する機能をサブクラスで実装するのがいいと思います。独自に作成したクラスのインスタンスは `Config#getSqlFileRepository()` で返すようにしてください。

この方法をとった場合、自動生成されるSQLについてはコメントを付与できません。しかし、パフォーマンスの問題が発生するのはほとんどの場合ファイルに記述したSQLだと思われますので、問題にならないと思います。

なお、付与するコメントですが、Domaに式コメントとして認識されないように `/** コメント */` のようにコメントの開始でアスタリスクを2つ続けてください。

### 今後の機能拡張に盛り込む案について

Doma 1には新機能を導入しない方針をとっているため、現段階では機能拡張の予定はありません（不具合の修正などは行います）。
Doma 2にはSQLに自由にコメントを付与する機能がすでに含まれているので、もし可能ならDoma 2を検討してもらえるとうれしいです。  [SQLの識別子の追記](http://doma.readthedocs.org/ja/stable/config/#id14)

**Comment by tatsus** [comment]
回答ありがとうございました。

教えていただいた方法で実装し、ファイルに記述したSQLにコメントを追加できました。

動作確認したソースコード
https://gist.github.com/tatsus/b7d445572bb160ee8171

Doma 2には既に機能があるのですね。前向きに検討したいと思います。

**Comment by nakamura-to** [comment]
:smile:
