### ISSUE TITLE
@infixについて

### ISSUE THREAD

**Issue by twan65** [seasarorg/doma#34]
お世話になります。

@infixについて質問となりますが、
Doma2では%abc%のように生成されるのでしょうか？
それとも%_abc_%のように生成されるのでしょうか？

よろしくお願いいたします。

**Comment by nakamura-to** [comment]
Doma1でもDoma2でも`%abc%`のように生成されます。
`%_abc_%`ではないですね。

勘違いされていると良くないので一応お伝えしますが、ここのリポジトリはDoma1のものです。
Doma2のリポジトリは以下のものになります。
https://github.com/domaframework/doma

**Comment by twan65** [comment]
ご回答いただきありがとうございます。
参考にできました。

リポジトリを読ませていただきます。
